### ISSUE TITLE
Using the same design for my website

### ISSUE THREAD

**Issue by Gitstar-OC** [vaibhav0806/okto-docs#1]
Hey vaibhav, this issue is being opened in this repo to ask you about the navigation bar. I liked the way you have styled the nvabar and added one for the navigation of the user instead of the typical one. 

So Can you keep this repository public for a few days or weeks as I will be refering to this codeblock. You can see my website at https://mindect.vercel.app. 

Thanks in advance.

**Comment by vaibhav0806** [comment]
@Gitstar-OC Hey, don't worry, I plan on keeping the repository public until the end of it, so rest assured
